// <auto-generated />
namespace HilbertsHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class useraddID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useraddID));
        
        string IMigrationMetadata.Id
        {
            get { return "201911012358556_user-addID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
